"""Channel definitions for Israel TV integration."""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class Channel:
    """Represents a single TV channel."""

    id: str
    name: str
    name_en: str
    category: str
    url: str
    # channel_type="yes_sport" triggers token-based scraping in media_source.py
    channel_type: str = "static"
    thumbnail: str | None = None


CATEGORY_LABELS: dict[str, str] = {
    "broadcast": "שידורי ישראל",
    "sport": "ספורט",
    "viva": "VIVA",
    "reality": "ריאליטי ותוכן",
    "music": "מוזיקה ובידור",
    "kids": "ילדים",
    "lifestyle": "לייפסטייל",
    "movies": "סרטים",
    "sport_global": "ספורט GLOBAL",
}

_CDN = "https://d1zqtf09wb8nt5.cloudfront.net/livehls/oil/freetv/live"

_LOGO_BASE = (
    "https://raw.githubusercontent.com/il90il90/hass-israel-tv"
    "/main/custom_components/israel_tv/logos/{}.png"
)


def _cdn(slug: str) -> str:
    # fmp4 gives modern fragmented-MP4 segments; omitting &renditions forces a
    # single fixed-quality stream so the player never switches quality mid-stream.
    return f"{_CDN}/{slug}/live.livx/playlist.m3u8?fmp4"


def _logo(name: str) -> str:
    """Return a GitHub-raw CDN URL for a logo PNG."""
    return _LOGO_BASE.format(name)


CHANNELS: list[Channel] = [
    # ── Broadcast ──────────────────────────────────────────────────────────────
    Channel(
        id="kan11",
        name="כאן 11",
        name_en="Channel 11",
        category="broadcast",
        url=_cdn("kan11"),
        thumbnail=_logo("kan11"),
    ),
    Channel(
        id="kan11_subs",
        name="כאן 11 כתוביות",
        name_en="Channel 11 Subtitles",
        category="broadcast",
        url=_cdn("kan11_subs"),
        thumbnail=_logo("kan11"),
    ),
    Channel(
        id="keshet_12",
        name="קשת 12",
        name_en="Channel 12",
        category="broadcast",
        url=_cdn("keshet_12"),
        thumbnail=_logo("keshet_12"),
    ),
    Channel(
        id="keshet_12_subs",
        name="קשת 12 כתוביות",
        name_en="Channel 12 Subtitles",
        category="broadcast",
        url=_cdn("keshet_12_subs"),
        thumbnail=_logo("keshet_12"),
    ),
    Channel(
        id="reshet_13",
        name="רשת 13",
        name_en="Channel 13",
        category="broadcast",
        url=_cdn("reshet_13"),
        thumbnail=_logo("reshet_13"),
    ),
    Channel(
        id="reshet_13_subs",
        name="רשת 13 כתוביות",
        name_en="Channel 13 Subtitles",
        category="broadcast",
        url=_cdn("reshet_13_subs"),
        thumbnail=_logo("reshet_13"),
    ),
    Channel(
        id="ch14",
        name="ערוץ 14",
        name_en="Channel 14",
        category="broadcast",
        url=_cdn("ch14"),
        thumbnail=_logo("ch14"),
    ),
    Channel(
        id="ch14_subs",
        name="ערוץ 14 כתוביות",
        name_en="Channel 14 Subtitles",
        category="broadcast",
        url=_cdn("ch14_subs"),
        thumbnail=_logo("ch14"),
    ),
    Channel(
        id="ch9",
        name="ערוץ 9",
        name_en="Channel 9",
        category="broadcast",
        url=_cdn("ch9"),
        thumbnail=_logo("ch9"),
    ),
    # ── Sport (Sport 5 + ONE + YES Sport — all under one folder) ───────────────
    Channel(
        id="sport_5",
        name="ספורט 5",
        name_en="Sport 5",
        category="sport",
        url=_cdn("sport_5"),
        thumbnail=_logo("sport_5"),
    ),
    Channel(
        id="sport_5_plus",
        name="ספורט 5 פלוס",
        name_en="Sport 5 Plus",
        category="sport",
        url=_cdn("sport_5_plus"),
        thumbnail=_logo("sport_5_plus"),
    ),
    Channel(
        id="sport_5_gold",
        name="ספורט 5 גולד",
        name_en="Sport 5 Gold",
        category="sport",
        url=_cdn("sport_5_gold"),
        thumbnail=_logo("sport_5_gold"),
    ),
    Channel(
        id="sport_5_live",
        name="ספורט 5 לייב",
        name_en="Sport 5 Live",
        category="sport",
        url=_cdn("sport_5_live"),
        thumbnail=_logo("sport_5_live"),
    ),
    Channel(
        id="sport_5_max",
        name="ספורט 5 מקס",
        name_en="Sport 5 Max",
        category="sport",
        url=_cdn("sport_5_max"),
        thumbnail=_logo("sport_5"),
    ),
    Channel(
        id="one_1",
        name="ONE 1",
        name_en="ONE 1",
        category="sport",
        url=_cdn("one_1"),
        thumbnail=_logo("one_1"),
    ),
    Channel(
        id="one_2",
        name="ONE 2",
        name_en="ONE 2",
        category="sport",
        url=_cdn("one_2"),
        thumbnail=_logo("one_2"),
    ),
    Channel(
        id="one_doco",
        name="ONE דוקו",
        name_en="ONE Doco",
        category="sport",
        url=_cdn("one_doco"),
        thumbnail=_logo("one_1"),
    ),
    Channel(
        id="one_edge",
        name="ONE אדג'",
        name_en="ONE Edge",
        category="sport",
        url=_cdn("one_edge"),
        thumbnail=_logo("one_1"),
    ),
    # Sport 1-4: token refreshed automatically via scraping
    Channel(
        id="yes1",
        name="ספורט 1",
        name_en="Sport 1",
        category="sport",
        url="",
        channel_type="yes_sport",
        thumbnail=_logo("yes1"),
    ),
    Channel(
        id="yes2",
        name="ספורט 2",
        name_en="Sport 2",
        category="sport",
        url="",
        channel_type="yes_sport",
        thumbnail=_logo("yes2"),
    ),
    Channel(
        id="yes3",
        name="ספורט 3",
        name_en="Sport 3",
        category="sport",
        url="",
        channel_type="yes_sport",
        thumbnail=_logo("yes3"),
    ),
    Channel(
        id="yes4",
        name="ספורט 4",
        name_en="Sport 4",
        category="sport",
        url="",
        channel_type="yes_sport",
        thumbnail=_logo("yes4"),
    ),
    # ── VIVA ───────────────────────────────────────────────────────────────────
    Channel(
        id="viva",
        name="VIVA",
        name_en="VIVA",
        category="viva",
        url=_cdn("viva"),
        thumbnail=_logo("viva"),
    ),
    Channel(
        id="viva_plus",
        name="VIVA פלוס",
        name_en="VIVA Plus",
        category="viva",
        url=_cdn("viva_plus"),
        thumbnail=_logo("viva_plus"),
    ),
    # ── Reality & Content ──────────────────────────────────────────────────────
    Channel(
        id="erez_nehederet",
        name="ארץ נהדרת",
        name_en="Eretz Nehederet",
        category="reality",
        url=_cdn("erez_nehederet"),
    ),
    Channel(
        id="vamos",
        name="וואמוס",
        name_en="Vamos",
        category="reality",
        url=_cdn("vamos"),
    ),
    # ── Music & Entertainment ──────────────────────────────────────────────────
    Channel(
        id="music24",
        name="מיוזיק 24",
        name_en="Music 24",
        category="music",
        url=_cdn("music24"),
    ),
    Channel(
        id="music_il",
        name="מיוזיק IL",
        name_en="Music IL",
        category="music",
        url=_cdn("music_il"),
        thumbnail=_logo("music_il"),
    ),
    Channel(
        id="karaoke",
        name="ערוץ הקריוקי",
        name_en="Karaoke Channel",
        category="music",
        url=_cdn("karaoke"),
    ),
    # ── Kids ───────────────────────────────────────────────────────────────────
    Channel(
        id="yoyo",
        name="יויו",
        name_en="Yoyo",
        category="kids",
        url=_cdn("yoyo"),
        thumbnail=_logo("yoyo"),
    ),
    Channel(
        id="logi",
        name="לוגי",
        name_en="Logi",
        category="kids",
        url=_cdn("logi"),
    ),
    Channel(
        id="yalduti",
        name="ילדותי",
        name_en="Yalduti",
        category="kids",
        url=_cdn("yalduti"),
    ),
    Channel(
        id="junior",
        name="ג'וניור",
        name_en="Junior",
        category="kids",
        url=_cdn("junior"),
        thumbnail=_logo("junior"),
    ),
    Channel(
        id="fomo",
        name="FOMO",
        name_en="FOMO",
        category="kids",
        url=_cdn("fomo"),
    ),
    # ── Lifestyle ──────────────────────────────────────────────────────────────
    Channel(
        id="hidabroot",
        name="הידברות",
        name_en="Hidabroot",
        category="lifestyle",
        url="https://htv-live.cybercdn.live/HidabrootIL/Live97/HidabrootIL/Live97_720p/chunks.m3u8",
        thumbnail=_logo("hidabroot"),
    ),
    Channel(
        id="foody",
        name="פודי",
        name_en="Foody",
        category="lifestyle",
        url=_cdn("foody"),
        thumbnail=_logo("foody"),
    ),
    Channel(
        id="beautyz",
        name="ביוטיז",
        name_en="Beautyz",
        category="lifestyle",
        url=_cdn("beautyz"),
    ),
    Channel(
        id="daystar",
        name="דייסטאר",
        name_en="Daystar",
        category="lifestyle",
        url=_cdn("daystar"),
    ),
    Channel(
        id="a_plus",
        name="A פלוס",
        name_en="A Plus",
        category="lifestyle",
        url=_cdn("a_plus"),
    ),
    # ── Movies ─────────────────────────────────────────────────────────────────
    Channel(
        id="30a_classic_movies",
        name="קלאסיקות 30A",
        name_en="30A Classic Movies",
        category="movies",
        url="https://30a-tv.com/feeds/pzaz/30atvmovies.m3u8",
    ),

    # ── Sport Global (iptv-org tested, HTTP 200 verified) ───────────────────────
    Channel(
        id="sg_30a_golf_kingdom",
        name="30A Golf Kingdom",
        name_en="30A Golf Kingdom",
        category="sport_global",
        url="https://30a-tv.com/feeds/vidaa/golf.m3u8",
    ),
    Channel(
        id="sg_accdn",
        name="ACCDN",
        name_en="ACCDN",
        category="sport_global",
        url="https://raycom-accdn-firetv.amagi.tv/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_accdn.png",
    ),
    Channel(
        id="sg_aci_sport_tv",
        name="ACI Sport TV",
        name_en="ACI Sport TV",
        category="sport_global",
        url="https://webstream.multistream.it/memfs/e2cb3629-c1a2-495b-b43a-9eb386f04ed8.m3u8",
        thumbnail="/israel_tv/logos/sg_aci_sport_tv.png",
    ),
    Channel(
        id="sg_ado_tv",
        name="ADO TV",
        name_en="ADO TV",
        category="sport_global",
        url="https://strhls.streamakaci.tv/ortb/ortb2-multi/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_ado_tv.png",
    ),
    Channel(
        id="sg_africa_24_sport",
        name="Africa 24 Sport",
        name_en="Africa 24 Sport",
        category="sport_global",
        url="https://africa24.vedge.infomaniak.com/livecast/ik:africa24sport/manifest.m3u8",
    ),
    Channel(
        id="sg_alkass_one",
        name="Alkass One",
        name_en="Alkass One",
        category="sport_global",
        channel_type="proxied",
        url="https://liveeu-gcp.alkassdigital.net/alkass1-p/main.m3u8",
        thumbnail="/israel_tv/logos/sg_alkass_one.png",
    ),
    Channel(
        id="sg_alkass_two",
        name="Alkass Two",
        name_en="Alkass Two",
        category="sport_global",
        channel_type="proxied",
        url="https://liveeu-gcp.alkassdigital.net/alkass2-p/main.m3u8",
        thumbnail="/israel_tv/logos/sg_alkass_two.png",
    ),
    Channel(
        id="sg_alkass_three",
        name="Alkass Three",
        name_en="Alkass Three",
        category="sport_global",
        channel_type="proxied",
        url="https://liveeu-gcp.alkassdigital.net/alkass3-p/main.m3u8",
        thumbnail="/israel_tv/logos/sg_alkass_three.png",
    ),
    Channel(
        id="sg_alkass_four",
        name="Alkass Four",
        name_en="Alkass Four",
        category="sport_global",
        channel_type="proxied",
        url="https://liveeu-gcp.alkassdigital.net/alkass4-p/main.m3u8",
        thumbnail="/israel_tv/logos/sg_alkass_four.png",
    ),
    Channel(
        id="sg_alkass_five",
        name="Alkass Five",
        name_en="Alkass Five",
        category="sport_global",
        channel_type="proxied",
        url="https://liveeu-gcp.alkassdigital.net/alkass5-p/main.m3u8",
        thumbnail="/israel_tv/logos/sg_alkass_five.png",
    ),
    Channel(
        id="sg_alkass_six",
        name="Alkass Six",
        name_en="Alkass Six",
        category="sport_global",
        channel_type="proxied",
        url="https://liveeu-gcp.alkassdigital.net/alkass6-p/main.m3u8",
        thumbnail="/israel_tv/logos/sg_alkass_six.png",
    ),
    Channel(
        id="sg_alkass_seven",
        name="Alkass Seven",
        name_en="Alkass Seven",
        category="sport_global",
        channel_type="proxied",
        url="https://liveeu-gcp.alkassdigital.net/alkass7-p/main.m3u8",
        thumbnail="/israel_tv/logos/sg_alkass_seven.png",
    ),
    Channel(
        id="sg_alkass_shoof",
        name="Alkass SHOOF",
        name_en="Alkass SHOOF",
        category="sport_global",
        channel_type="proxied",
        url="https://liveeu-gcp.alkassdigital.net/shooflive/main.m3u8",
        thumbnail="/israel_tv/logos/sg_alkass_shoof.png",
    ),
    Channel(
        id="sg_alkass_shoof_2",
        name="Alkass SHOOF 2",
        name_en="Alkass SHOOF 2",
        category="sport_global",
        channel_type="proxied",
        url="https://liveeu-gcp.alkassdigital.net/shooflive2/main.m3u8",
        thumbnail="/israel_tv/logos/sg_alkass_shoof_2.png",
    ),
    Channel(
        id="sg_as3_sport_tv",
        name="AS3 Sport TV",
        name_en="AS3 Sport TV",
        category="sport_global",
        url="https://streamtv.as3sport.online:3394/hybrid/play.m3u8",
        thumbnail="/israel_tv/logos/sg_as3_sport_tv.png",
    ),
    Channel(
        id="sg_atg_live",
        name="ATG Live",
        name_en="ATG Live",
        category="sport_global",
        url="https://kanal75xto-llhls.akamaized.net/live/Data/atg-kanal-15-02a-rr/HLS-Legacy-HL/atg-kanal-15-02a-rr.m3u8",
        thumbnail="/israel_tv/logos/sg_atg_live.png",
    ),
    Channel(
        id="sg_bahrain_sports_1",
        name="Bahrain Sports 1",
        name_en="Bahrain Sports 1",
        category="sport_global",
        url="https://5c7b683162943.streamlock.net/live/ngrp:sportsone_all/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_bahrain_sports_1.png",
    ),
    Channel(
        id="sg_bahrain_sports_2",
        name="Bahrain Sports 2",
        name_en="Bahrain Sports 2",
        category="sport_global",
        url="https://5c7b683162943.streamlock.net/live/ngrp:bahrainsportstwo_all/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_bahrain_sports_2.png",
    ),
    Channel(
        id="sg_bein_sports_xtra_es",
        name="beIN Sports XTRA en Espanol",
        name_en="beIN Sports XTRA en Espanol",
        category="sport_global",
        url="https://dc1644a9jazgj.cloudfront.net/beIN_Sports_Xtra_Espanol.m3u8",
        thumbnail="/israel_tv/logos/sg_bein_sports_xtra_es.png",
    ),
    Channel(
        id="sg_bek_tv_sports_west",
        name="BEK TV Sports West",
        name_en="BEK TV Sports West",
        category="sport_global",
        url="https://cdn3.wowza.com/5/ZWQ1K2NYTmpFbGsr/BEK-WOWZA-1/smil:BEKPRIMEW.smil/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_bek_tv_sports_west.png",
    ),
    Channel(
        id="sg_bellator_mma",
        name="Bellator MMA",
        name_en="Bellator MMA",
        category="sport_global",
        url="https://jmp2.uk/plu-5ebc8688f3697d00072f7cf8.m3u8",
        thumbnail="/israel_tv/logos/sg_bellator_mma.png",
    ),
    Channel(
        id="sg_cazetv",
        name="CazeTV",
        name_en="CazeTV",
        category="sport_global",
        url="https://dfr80qz435crc.cloudfront.net/MNOP/Amagi/Caze/Caze_TV_BR/Caze_TV.m3u8",
        thumbnail="/israel_tv/logos/sg_cazetv.png",
    ),
    Channel(
        id="sg_cctv_16",
        name="CCTV-16",
        name_en="CCTV-16",
        category="sport_global",
        url="http://74.91.26.218:82/live/cctv16hd.m3u8",
        thumbnail="/israel_tv/logos/sg_cctv_16.png",
    ),
    Channel(
        id="sg_cdn_deportes",
        name="CDN Deportes",
        name_en="CDN Deportes",
        category="sport_global",
        url="http://200.125.170.122:8000/play/a03j/index.m3u8",
        thumbnail="/israel_tv/logos/sg_cdn_deportes.png",
    ),
    Channel(
        id="sg_colimdot_tv",
        name="ColimdoT TV",
        name_en="ColimdoT TV",
        category="sport_global",
        url="https://cnn.livestreaminggroup.info:3132/live/colimdotvlive.m3u8",
        thumbnail="/israel_tv/logos/sg_colimdot_tv.png",
    ),
    Channel(
        id="sg_cricket_gold",
        name="Cricket Gold",
        name_en="Cricket Gold",
        category="sport_global",
        url="https://streams2.sofast.tv/scheduler/scheduleMaster/418.m3u8",
        thumbnail="/israel_tv/logos/sg_cricket_gold.png",
    ),
    Channel(
        id="sg_ct_sport",
        name="ČT Sport",
        name_en="CT Sport",
        category="sport_global",
        url="http://88.212.15.19/live/test_ctsport_25p/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_ct_sport.png",
    ),
    Channel(
        id="sg_dazn_combat",
        name="DAZN Combat",
        name_en="DAZN Combat",
        category="sport_global",
        url="https://dazn-combat-rakuten.amagi.tv/hls/amagi_hls_data_rakutenAA-dazn-combat-rakuten/CDN/master.m3u8",
        thumbnail="/israel_tv/logos/sg_dazn_combat.png",
    ),
    Channel(
        id="sg_dd_sports_sd",
        name="DD Sports SD",
        name_en="DD Sports SD",
        category="sport_global",
        url="https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/b17adfe543354fdd8d189b110617cddd/index.m3u8",
        thumbnail="/israel_tv/logos/sg_dd_sports_sd.png",
    ),
    Channel(
        id="sg_dong_nai_2",
        name="Đồng Nai 2",
        name_en="Dong Nai 2",
        category="sport_global",
        url="http://118.107.85.4:1935/live/smil:DNTV2.smil/chunklist.m3u8",
        thumbnail="/israel_tv/logos/sg_dong_nai_2.png",
    ),
    Channel(
        id="sg_draftkings_network",
        name="DraftKings Network",
        name_en="DraftKings Network",
        category="sport_global",
        url="https://na.linear.zype.com/e0bd0e23-a958-4e43-8164-4f2fef8876a8/fd3614bd-90bf-4530-a277-65ae3a1720c8-zype/live.m3u8",
        thumbnail="/israel_tv/logos/sg_draftkings_network.png",
    ),
    Channel(
        id="sg_equidia",
        name="Equidia",
        name_en="Equidia",
        category="sport_global",
        url="https://raw.githubusercontent.com/Paradise-91/ParaTV/main/streams/equidia/live2.m3u8",
        thumbnail="/israel_tv/logos/sg_equidia.png",
    ),
    Channel(
        id="sg_ert_sports_1",
        name="ERT Sports 1",
        name_en="ERT Sports 1",
        category="sport_global",
        url="http://hbbtvapp.ert.gr/stream.php/v/vid_ertsports_mpeg.2ts",
        thumbnail="/israel_tv/logos/sg_ert_sports_1.png",
    ),
    Channel(
        id="sg_ert_sports_2",
        name="ERT Sports 2",
        name_en="ERT Sports 2",
        category="sport_global",
        url="http://hbbtvapp.ert.gr/stream.php/v/vid_ertplay2_mpeg.2ts",
        thumbnail="/israel_tv/logos/sg_ert_sports_2.png",
    ),
    Channel(
        id="sg_espn8_the_ocho",
        name="ESPN8 The Ocho",
        name_en="ESPN8 The Ocho",
        category="sport_global",
        url="https://d3b6q2ou5kp8ke.cloudfront.net/ESPNTheOcho.m3u8",
        thumbnail="/israel_tv/logos/sg_espn8_the_ocho.png",
    ),
    Channel(
        id="sg_esport3",
        name="Esport3",
        name_en="Esport3",
        category="sport_global",
        url="https://directes-tv-int.3catdirectes.cat/live-content/esport3-hls/master.m3u8",
        thumbnail="/israel_tv/logos/sg_esport3.png",
    ),
    Channel(
        id="sg_fanduel_racing",
        name="FanDuel Racing",
        name_en="FanDuel Racing",
        category="sport_global",
        url="https://d3ehq1uaxory6w.cloudfront.net/out/v1/35c05f080f4e49a4b4eb031b5a14e505/TVG2index_2.m3u8",
        thumbnail="/israel_tv/logos/sg_fanduel_racing.png",
    ),
    Channel(
        id="sg_fanduel_tv",
        name="FanDuel TV",
        name_en="FanDuel TV",
        category="sport_global",
        url="https://d2jl8r92tdc3f1.cloudfront.net/out/v1/59419700344b4625b7cb0693ba265ea3/TVGindex_1.m3u8",
        thumbnail="/israel_tv/logos/sg_fanduel_tv.png",
    ),
    Channel(
        id="sg_fb_tv",
        name="FB TV (Fenerbahce)",
        name_en="FB TV",
        category="sport_global",
        url="http://1hskrdto.rocketcdn.com/fenerbahcetv.smil/playlist.m3u8",
        thumbnail="https://i.imgur.com/qBVqtYd.png",
    ),
    Channel(
        id="sg_floracing_247",
        name="FloRacing 24/7",
        name_en="FloRacing 24/7",
        category="sport_global",
        url="https://amg02278-amg02278c1-flosports-worldwide-7592.playouts.now.amagi.tv/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_floracing_247.png",
    ),
    Channel(
        id="sg_fox_sports",
        name="Fox Sports",
        name_en="Fox Sports",
        category="sport_global",
        url="http://201.217.246.42:44310/Live/b10474c9b1ba4a0986b574d1211c065b/local-91.playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_fox_sports.png",
    ),
    Channel(
        id="sg_fox_sports_es",
        name="Fox Sports en Espanol",
        name_en="Fox Sports en Espanol",
        category="sport_global",
        url="https://live-manifest.production-public.tubi.io/live/d906efca-1302-4e29-b0d9-9a1d7a305d69/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_fox_sports_es.png",
    ),
    Channel(
        id="sg_ftf_sports",
        name="FTF Sports",
        name_en="FTF Sports",
        category="sport_global",
        url="https://1657061170.rsc.cdn77.org/HLS/FTF-LINEAR.m3u8",
        thumbnail="/israel_tv/logos/sg_ftf_sports.png",
    ),
    Channel(
        id="sg_ftv",
        name="FTV",
        name_en="FTV",
        category="sport_global",
        url="https://master.tucableip.com/ftvhd/index.m3u8",
        thumbnail="/israel_tv/logos/sg_ftv.png",
    ),
    Channel(
        id="sg_fubo_sports",
        name="fubo Sports Network",
        name_en="fubo Sports Network",
        category="sport_global",
        url="https://dnf08l6u6uxnz.cloudfront.net/master.m3u8",
        thumbnail="/israel_tv/logos/sg_fubo_sports.png",
    ),
    Channel(
        id="sg_fuel_tv",
        name="Fuel TV",
        name_en="Fuel TV",
        category="sport_global",
        url="https://amg01074-fueltv-fueltvau-samsungau-g09kq.amagi.tv/playlist/amg01074-fueltv-fueltvau-samsungau/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_fuel_tv.png",
    ),
    Channel(
        id="sg_fuel_tv_emea",
        name="FUEL TV EMEA",
        name_en="FUEL TV EMEA",
        category="sport_global",
        url="https://amg01074-fueltv-fueltvemeaen-rakuten-b6j62.amagi.tv/hls/amagi_hls_data_rakutenAA-fueltvemeaen/CDN/master.m3u8",
        thumbnail="/israel_tv/logos/sg_fuel_tv_emea.png",
    ),
    Channel(
        id="sg_futbol",
        name="Futbol",
        name_en="Futbol",
        category="sport_global",
        url="https://live.teleradiocom.tj/8/3m.m3u8",
        thumbnail="/israel_tv/logos/sg_futbol.png",
    ),
    Channel(
        id="sg_game_plus",
        name="Game+",
        name_en="Game+",
        category="sport_global",
        url="https://a-cdn.klowdtv.com/live2/fntsy_720p/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_game_plus.png",
    ),
    Channel(
        id="sg_gem_fit",
        name="GEM Fit",
        name_en="GEM Fit",
        category="sport_global",
        url="https://ca-rt.onetv.app/gemfit/index-0.m3u8?token=onetv202",
        thumbnail="/israel_tv/logos/sg_gem_fit.png",
    ),
    Channel(
        id="sg_goal_zone",
        name="Goal Zone",
        name_en="Goal Zone",
        category="sport_global",
        url="https://shls-live-enc.edgenextcdn.net/out/v1/18cffab0757d448ca6c1a686d330b346/index.m3u8",
        thumbnail="/israel_tv/logos/sg_goal_zone.png",
    ),
    Channel(
        id="sg_gol_classics",
        name="Gol Classics",
        name_en="Gol Classics",
        category="sport_global",
        url="https://d71gqtnep83vb.cloudfront.net/gol_classics/gol_classics.m3u8",
    ),
    Channel(
        id="sg_golf_channel_latam",
        name="Golf Channel Latin America",
        name_en="Golf Channel Latin America",
        category="sport_global",
        url="http://181.114.57.246:4000/play/BHGDIhvdyuw/index.m3u8",
        thumbnail="/israel_tv/logos/sg_golf_channel_latam.png",
    ),
    Channel(
        id="sg_horse_tv",
        name="Horse TV",
        name_en="Horse TV",
        category="sport_global",
        url="https://a-cdn.klowdtv.com/live2/horsetv_720p/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_horse_tv.png",
    ),
    Channel(
        id="sg_htspor_tv",
        name="HTSpor TV",
        name_en="HTSpor TV",
        category="sport_global",
        url="https://ciner.daioncdn.net/ht-spor/ht-spor.m3u8?app=web",
        thumbnail="/israel_tv/logos/sg_htspor_tv.png",
    ),
    Channel(
        id="sg_introuble",
        name="INTROUBLE",
        name_en="INTROUBLE",
        category="sport_global",
        url="https://amg00861-amg00861c6-stirr-us-8229.playouts.now.amagi.tv/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_introuble.png",
    ),
    Channel(
        id="sg_itv_deportes",
        name="ITV Deportes",
        name_en="ITV Deportes",
        category="sport_global",
        url="https://thm-it-roku.otteravision.com/thm/it/it.m3u8",
        thumbnail="/israel_tv/logos/sg_itv_deportes.png",
    ),
    Channel(
        id="sg_jordan_sport",
        name="Jordan Sport",
        name_en="Jordan Sport",
        category="sport_global",
        url="http://93.184.10.248/JordanSport/index.m3u8",
        thumbnail="/israel_tv/logos/sg_jordan_sport.png",
    ),
    Channel(
        id="sg_kcmn_ld6",
        name="KCMN-LD6",
        name_en="KCMN-LD6",
        category="sport_global",
        url="https://cdn-uw2-prod.tsv2.amagi.tv/linear/amg02873-kravemedia-mtrspt1-distrotv/playlist.m3u8",
    ),
    Channel(
        id="sg_khl",
        name="KHL",
        name_en="KHL",
        category="sport_global",
        url="http://31.148.48.15/KHL_TV/index.m3u8",
        thumbnail="/israel_tv/logos/sg_khl.png",
    ),
    Channel(
        id="sg_khl_prime",
        name="KHL Prime",
        name_en="KHL Prime",
        category="sport_global",
        url="http://31.148.48.15/KHL_TV_HD/index.m3u8",
        thumbnail="/israel_tv/logos/sg_khl_prime.png",
    ),
    Channel(
        id="sg_ktv_sport",
        name="KTV Sport",
        name_en="KTV Sport",
        category="sport_global",
        url="https://kwtspta.cdn.mangomolo.com/sp/smil:sp.stream.smil/chunklist.m3u8",
        thumbnail="/israel_tv/logos/sg_ktv_sport.png",
    ),
    Channel(
        id="sg_ktv_sport_plus",
        name="KTV Sport Plus",
        name_en="KTV Sport Plus",
        category="sport_global",
        url="https://kwtsplta.cdn.mangomolo.com/spl/smil:spl.stream.smil/chunklist.m3u8",
        thumbnail="/israel_tv/logos/sg_ktv_sport_plus.png",
    ),
    Channel(
        id="sg_lucha_libre_aaa",
        name="Lucha Libre AAA",
        name_en="Lucha Libre AAA",
        category="sport_global",
        url="https://jmp2.uk/plu-5c01df1759ee03633e7b272c.m3u8",
        thumbnail="/israel_tv/logos/sg_lucha_libre_aaa.png",
    ),
    Channel(
        id="sg_madeinbo_tv",
        name="MadeinBO TV",
        name_en="MadeinBO TV",
        category="sport_global",
        url="https://srvx1.selftv.video/dmchannel/live/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_madeinbo_tv.png",
    ),
    Channel(
        id="sg_match_strana",
        name="Match! Strana",
        name_en="Match! Strana",
        category="sport_global",
        url="http://31.148.48.15/Match_Strana/index.m3u8",
        thumbnail="/israel_tv/logos/sg_match_strana.png",
    ),
    Channel(
        id="sg_mma_tv_com",
        name="MMA TV.com",
        name_en="MMA TV.com",
        category="sport_global",
        url="https://streams2.sofast.tv/vglive-sk-462904/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_mma_tv_com.png",
    ),
    Channel(
        id="sg_mma_tv",
        name="MMA-TV",
        name_en="MMA-TV",
        category="sport_global",
        url="http://31.148.48.15/M1_Global/index.m3u8",
        thumbnail="/israel_tv/logos/sg_mma_tv.png",
    ),
    Channel(
        id="sg_mnb_sport",
        name="MNB Sport",
        name_en="MNB Sport",
        category="sport_global",
        url="https://live.mnb.mn/hls/mnb_sport.stream.m3u8",
        thumbnail="/israel_tv/logos/sg_mnb_sport.png",
    ),
    Channel(
        id="sg_monterrico_tv",
        name="Monterrico TV",
        name_en="Monterrico TV",
        category="sport_global",
        url="https://www.opencaster.com/resources/hls_stream/hipodromojcp2.m3u8",
        thumbnail="/israel_tv/logos/sg_monterrico_tv.png",
    ),
    Channel(
        id="sg_more_than_sports",
        name="More Than Sports TV",
        name_en="More Than Sports TV",
        category="sport_global",
        url="https://mts1.iptv-playoutcenter.de/mts/mts-web/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_more_than_sports.png",
    ),
    Channel(
        id="sg_multivision_sports",
        name="Multivisión Sports",
        name_en="Multivision Sports",
        category="sport_global",
        url="https://stream.digitalgt.com:3605/live/multivisionsportslive.m3u8",
        thumbnail="/israel_tv/logos/sg_multivision_sports.png",
    ),
    Channel(
        id="sg_nautical_channel",
        name="Nautical Channel",
        name_en="Nautical Channel",
        category="sport_global",
        url="https://a-cdn.klowdtv.com/live2/nautical_720p/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_nautical_channel.png",
    ),
    Channel(
        id="sg_nhra_tv",
        name="NHRA TV",
        name_en="NHRA TV",
        category="sport_global",
        url="https://d265y4sk8257lt.cloudfront.net/nh.m3u8",
        thumbnail="/israel_tv/logos/sg_nhra_tv.png",
    ),
    Channel(
        id="sg_nudge_sports",
        name="Nudge Sports Channel",
        name_en="Nudge Sports Channel",
        category="sport_global",
        url="https://streams.comclark.com/live_input/nudge_sports/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_nudge_sports.png",
    ),
    Channel(
        id="sg_oman_sports_tv",
        name="Oman Sports TV",
        name_en="Oman Sports TV",
        category="sport_global",
        url="https://partneta.cdn.mgmlcdn.com/omsport/smil:omsport.stream.smil/chunklist.m3u8",
        thumbnail="/israel_tv/logos/sg_oman_sports_tv.png",
    ),
    Channel(
        id="sg_ovacion_tv",
        name="Ovacion TV",
        name_en="Ovacion TV",
        category="sport_global",
        url="http://cdn2.ujjina.com:1935/iptvovacion1/liveovacion1tv/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_ovacion_tv.png",
    ),
    Channel(
        id="sg_overtime",
        name="Overtime",
        name_en="Overtime",
        category="sport_global",
        url="https://d1a8aq6t30gkqj.cloudfront.net/v1/amc_overtime_1/samsungheadend_us/latest/main/hls/playlist_hd.m3u8",
        thumbnail="/israel_tv/logos/sg_overtime.png",
    ),
    Channel(
        id="sg_pac12_insider",
        name="Pac 12 Insider",
        name_en="Pac 12 Insider",
        category="sport_global",
        url="https://pac12-firetv.amagi.tv/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_pac12_insider.png",
    ),
    Channel(
        id="sg_pbr_ridepass",
        name="PBR RidePass",
        name_en="PBR RidePass",
        category="sport_global",
        url="https://jmp2.uk/plu-60d39387706fe50007fda8e8.m3u8",
        thumbnail="/israel_tv/logos/sg_pbr_ridepass.png",
    ),
    Channel(
        id="sg_persiana_fight",
        name="Persiana Fight",
        name_en="Persiana Fight",
        category="sport_global",
        url="https://fighthls.persiana.live/hls/stream.m3u8",
    ),
    Channel(
        id="sg_pga_tour",
        name="PGA Tour",
        name_en="PGA Tour",
        category="sport_global",
        url="https://d11k1mnrgfposz.cloudfront.net/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_pga_tour.png",
    ),
    Channel(
        id="sg_pluto_futbol",
        name="Pluto TV Futbol Para Fans",
        name_en="Pluto TV Futbol Para Fans",
        category="sport_global",
        url="https://jmp2.uk/plu-63c6e37e636b7e0007ccb635.m3u8",
        thumbnail="/israel_tv/logos/sg_pluto_futbol.png",
    ),
    Channel(
        id="sg_polsat_sport_2",
        name="Polsat Sport Premium 2",
        name_en="Polsat Sport Premium 2",
        category="sport_global",
        url="http://78.130.250.2:8023/play/a05r/index.m3u8",
        thumbnail="/israel_tv/logos/sg_polsat_sport_2.png",
    ),
    Channel(
        id="sg_qazsport",
        name="QazSport",
        name_en="QazSport",
        category="sport_global",
        url="https://qazsporttv-stream.qazcdn.com/qazsporttv/qazsporttv/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_qazsport.png",
    ),
    Channel(
        id="sg_racer_intl",
        name="RACER International",
        name_en="RACER International",
        category="sport_global",
        url="https://amg00378-mavtv-amg00378c2-rakuten-us-1048.playouts.now.amagi.tv/playlist/amg00378-mavtvfast-motorsportsnetwork-rakutenus/playlist.m3u8",
    ),
    Channel(
        id="sg_racer_select",
        name="Racer Select",
        name_en="Racer Select",
        category="sport_global",
        url="https://amg00378-amg00378c4-freelivesports-emea-5637.playouts.now.amagi.tv/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_racer_select.png",
    ),
    Channel(
        id="sg_realmadrid_tv",
        name="Realmadrid TV",
        name_en="Realmadrid TV",
        category="sport_global",
        url="https://jmp2.uk/plu-63dac28760bc8f0008a7654b.m3u8",
        thumbnail="/israel_tv/logos/sg_realmadrid_tv.png",
    ),
    Channel(
        id="sg_red_bull_tv",
        name="Red Bull TV",
        name_en="Red Bull TV",
        category="sport_global",
        url="https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8",
        thumbnail="/israel_tv/logos/sg_red_bull_tv.png",
    ),
    Channel(
        id="sg_rti_la_3",
        name="RTI La 3",
        name_en="RTI La 3",
        category="sport_global",
        url="http://69.64.57.208/la3/index.m3u8",
        thumbnail="/israel_tv/logos/sg_rti_la_3.png",
    ),
    Channel(
        id="sg_san_marino_rtv",
        name="San Marino RTV Sport",
        name_en="San Marino RTV Sport",
        category="sport_global",
        url="https://d2hrvno5bw6tg2.cloudfront.net/smrtv-ch02/smil:ch-02.smil/master.m3u8",
        thumbnail="/israel_tv/logos/sg_san_marino_rtv.png",
    ),
    Channel(
        id="sg_sky_racing_1",
        name="Sky Racing 1",
        name_en="Sky Racing 1",
        category="sport_global",
        url="https://636ffd31f0e12.streamlock.net/RacingStream1/RacingStream1/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_sky_racing_1.png",
    ),
    Channel(
        id="sg_sky_racing_2",
        name="Sky Racing 2",
        name_en="Sky Racing 2",
        category="sport_global",
        url="https://636ffd31f0e12.streamlock.net/RacingStream2/RacingStream2/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_sky_racing_2.png",
    ),
    Channel(
        id="sg_sport_1",
        name="Sport 1",
        name_en="Sport 1",
        category="sport_global",
        url="http://46.149.191.217:9005/play/a017",
        thumbnail="/israel_tv/logos/sg_sport_1.png",
    ),
    Channel(
        id="sg_sport_italia",
        name="Sport Italia",
        name_en="Sport Italia",
        category="sport_global",
        url="https://amg01370-italiansportcom-sportitalia-rakuten-3hmdb.amagi.tv/hls/amagi_hls_data_rakutenAA-sportitalia-rakuten/CDN/master.m3u8",
        thumbnail="/israel_tv/logos/sg_sport_italia.png",
    ),
    Channel(
        id="sg_sports_connect",
        name="Sports Connect",
        name_en="Sports Connect",
        category="sport_global",
        url="https://streamdot.broadpeak.io/cff02a74da64d1459391ce1f72d58f1a/afxpstr/SportsConnect/index.m3u8",
        thumbnail="/israel_tv/logos/sg_sports_connect.png",
    ),
    Channel(
        id="sg_stadium",
        name="Stadium",
        name_en="Stadium",
        category="sport_global",
        url="https://wurl120sports.global.transmit.live/hls/679a907dce42a042c23ace37/v1/stadium_gracenote/samsung_us/latest/main/hls/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_stadium.png",
    ),
    Channel(
        id="sg_star_sports_1_hd",
        name="Star Sports 1 HD",
        name_en="Star Sports 1 HD",
        category="sport_global",
        url="http://103.253.18.58:8000/play/a00m",
        thumbnail="/israel_tv/logos/sg_star_sports_1_hd.png",
    ),
    Channel(
        id="sg_star_sports_1_hindi",
        name="Star Sports 1 Hindi",
        name_en="Star Sports 1 Hindi",
        category="sport_global",
        url="http://103.253.18.58:8000/play/a03o",
        thumbnail="/israel_tv/logos/sg_star_sports_1_hindi.png",
    ),
    Channel(
        id="sg_star_sports_2_hindi_hd",
        name="Star Sports 2 Hindi HD",
        name_en="Star Sports 2 Hindi HD",
        category="sport_global",
        url="http://103.157.248.140:8000/play/a01m/index.m3u8",
        thumbnail="/israel_tv/logos/sg_star_sports_2_hindi_hd.png",
    ),
    Channel(
        id="sg_strongman",
        name="Strongman",
        name_en="Strongman",
        category="sport_global",
        url="https://rightsboosterltd-scl-1-eu.rakuten.wurl.tv/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_strongman.png",
    ),
    Channel(
        id="sg_strongman_champions",
        name="Strongman Champions League",
        name_en="Strongman Champions League",
        category="sport_global",
        url="https://rightsboosterltd-scl-2-eu.rakuten.wurl.tv/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_strongman_champions.png",
    ),
    Channel(
        id="sg_suspilne_sport",
        name="Suspilne Sport",
        name_en="Suspilne Sport",
        category="sport_global",
        url="https://cdnua05.hls.tv/934/hls/8743361621b245838bee193c9ec28322/4856/stream.m3u8",
        thumbnail="/israel_tv/logos/sg_suspilne_sport.png",
    ),
    Channel(
        id="sg_swerve_combat",
        name="Swerve Combat",
        name_en="Swerve Combat",
        category="sport_global",
        url="https://linear-253.frequency.stream/mt/roku/253/hls/master/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_swerve_combat.png",
    ),
    Channel(
        id="sg_talent_tv",
        name="Talent TV",
        name_en="Talent TV",
        category="sport_global",
        url="http://live.talenttv.lk:8080/hls/x8kd5n3tm8e8lsv/index.m3u8",
        thumbnail="/israel_tv/logos/sg_talent_tv.png",
    ),
    Channel(
        id="sg_tele_rebelde",
        name="Tele Rebelde",
        name_en="Tele Rebelde",
        category="sport_global",
        url="https://tv.picta.cu/telerebelde/telerebelde_1.m3u8",
        thumbnail="/israel_tv/logos/sg_tele_rebelde.png",
    ),
    Channel(
        id="sg_teledeporte",
        name="Teledeporte",
        name_en="Teledeporte",
        category="sport_global",
        url="https://rtvelivestream.rtve.es/rtvesec/tdp/tdp_main.m3u8",
        thumbnail="/israel_tv/logos/sg_teledeporte.png",
    ),
    Channel(
        id="sg_teletrak",
        name="Teletrak",
        name_en="Teletrak",
        category="sport_global",
        url="https://unlimited6-cl.dps.live/sportinghd/sportinghd.smil/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_teletrak.png",
    ),
    Channel(
        id="sg_tennis_channel",
        name="Tennis Channel",
        name_en="Tennis Channel",
        category="sport_global",
        url="https://cdn-ue1-prod.tsv2.amagi.tv/linear/amg01444-tennischannelth-tennischannelnl-samsungnl/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_tennis_channel.png",
    ),
    Channel(
        id="sg_tennis_channel_2",
        name="Tennis Channel 2",
        name_en="Tennis Channel 2",
        category="sport_global",
        url="https://jmp2.uk/plu-681109b688b9d85d0938c6ba.m3u8",
        thumbnail="/israel_tv/logos/sg_tennis_channel_2.png",
    ),
    Channel(
        id="sg_thmanyah_1",
        name="Thmanyah 1",
        name_en="Thmanyah 1",
        category="sport_global",
        url="https://dflive.app.tc/20.m3u8",
        thumbnail="/israel_tv/logos/sg_thmanyah_1.png",
    ),
    Channel(
        id="sg_tigo_sports_plus",
        name="Tigo Sports+",
        name_en="Tigo Sports+",
        category="sport_global",
        url="http://45.170.130.224:8000/play/a04i/index.m3u8",
        thumbnail="/israel_tv/logos/sg_tigo_sports_plus.png",
    ),
    Channel(
        id="sg_tjk_tv",
        name="TJK TV",
        name_en="TJK TV",
        category="sport_global",
        url="https://tjktv-live.tjk.org/tjktv.m3u8",
        thumbnail="/israel_tv/logos/sg_tjk_tv.png",
    ),
    Channel(
        id="sg_tour_spot_tv",
        name="Tour Spot TV",
        name_en="Tour Spot TV",
        category="sport_global",
        url="https://fox.hostlagarto.com:8081/toursporttv/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_tour_spot_tv.png",
    ),
    Channel(
        id="sg_tr_sport",
        name="TR Sport",
        name_en="TR Sport",
        category="sport_global",
        url="https://livetr.teleromagna.it/mia/live/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_tr_sport.png",
    ),
    Channel(
        id="sg_trace_sport_stars_au",
        name="Trace Sport Stars (Australia)",
        name_en="Trace Sport Stars Australia",
        category="sport_global",
        url="https://lightning-tracesport-samsungau.amagi.tv/playlist.m3u8",
        thumbnail="https://i.imgur.com/FabFP5A.png",
    ),
    Channel(
        id="sg_turf_movil",
        name="Turf Movil",
        name_en="Turf Movil",
        category="sport_global",
        url="https://tvturf4.janus.cl/playlist/stream.m3u8?d=w&id=",
        thumbnail="/israel_tv/logos/sg_turf_movil.png",
    ),
    Channel(
        id="sg_turkmenistan_sport",
        name="Türkmenistan Sport",
        name_en="Turkmenistan Sport",
        category="sport_global",
        url="https://alpha.tv.online.tm/hls/ch004.m3u8",
        thumbnail="/israel_tv/logos/sg_turkmenistan_sport.png",
    ),
    Channel(
        id="sg_tvr_sport",
        name="TVR Sport",
        name_en="TVR Sport",
        category="sport_global",
        url="https://tvr-sport.lg.mncdn.com/tvrsport/smil:tvrsport.smil/chunklist_b5160000.m3u8",
        thumbnail="/israel_tv/logos/sg_tvr_sport.png",
    ),
    Channel(
        id="sg_tvri_sport",
        name="TVRI Sport",
        name_en="TVRI Sport",
        category="sport_global",
        url="https://ott-balancer.tvri.go.id/live/eds/SportHD/hls/SportHD.m3u8",
    ),
    Channel(
        id="sg_tvs_bowling",
        name="TVS Bowling Network",
        name_en="TVS Bowling Network",
        category="sport_global",
        url="https://rpn.bozztv.com/gusa/gusa-tvsbowling/index.m3u8",
        thumbnail="/israel_tv/logos/sg_tvs_bowling.png",
    ),
    Channel(
        id="sg_tvs_boxing",
        name="TVS Boxing",
        name_en="TVS Boxing",
        category="sport_global",
        url="https://rpn.bozztv.com/gusa/gusa-tvsboxing/index.m3u8",
        thumbnail="/israel_tv/logos/sg_tvs_boxing.png",
    ),
    Channel(
        id="sg_tvs_classic_sports",
        name="TVS Classic Sports",
        name_en="TVS Classic Sports",
        category="sport_global",
        url="https://rpn.bozztv.com/gusa/gusa-tvs/index.m3u8",
        thumbnail="/israel_tv/logos/sg_tvs_classic_sports.png",
    ),
    Channel(
        id="sg_tvs_sports",
        name="TVS Sports",
        name_en="TVS Sports",
        category="sport_global",
        url="https://rpn.bozztv.com/gusa/gusa-tvssports/index.m3u8",
        thumbnail="/israel_tv/logos/sg_tvs_sports.png",
    ),
    Channel(
        id="sg_tvs_sports_bureau",
        name="TVS Sports Bureau",
        name_en="TVS Sports Bureau",
        category="sport_global",
        url="https://rpn.bozztv.com/gusa/gusa-tvssportsbureau/index.m3u8",
    ),
    Channel(
        id="sg_tvs_turbo",
        name="TVS Turbo",
        name_en="TVS Turbo",
        category="sport_global",
        url="https://rpn.bozztv.com/gusa/gusa-tvsturbo/index.m3u8",
        thumbnail="/israel_tv/logos/sg_tvs_turbo.png",
    ),
    Channel(
        id="sg_tvs_women_sports",
        name="TVS Women Sports",
        name_en="TVS Women Sports",
        category="sport_global",
        url="https://rpn.bozztv.com/gusa/gusa-tvswsn/index.m3u8",
        thumbnail="/israel_tv/logos/sg_tvs_women_sports.png",
    ),
    Channel(
        id="sg_tyc_sports",
        name="TyC Sports",
        name_en="TyC Sports",
        category="sport_global",
        url="https://amg26268-amg26268c14-freelivesports-emea-10267.playouts.now.amagi.tv/ts-us-e2-n2/playlist/amg26268-sportsstudio-tycsports-freelivesportsemea/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_tyc_sports.png",
    ),
    Channel(
        id="sg_tyc_sports_latam",
        name="TyC Sports Latin America",
        name_en="TyC Sports Latin America",
        category="sport_global",
        url="http://201.217.246.42:44310/Live/d93a7c495cb5f5d236b25a3ffea95003/local-90.playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_tyc_sports_latam.png",
    ),
    Channel(
        id="sg_tyc_sports_usa",
        name="TyC Sports USA",
        name_en="TyC Sports USA",
        category="sport_global",
        url="http://45.170.130.224:8000/play/a020/index.m3u8",
        thumbnail="/israel_tv/logos/sg_tyc_sports_usa.png",
    ),
    Channel(
        id="sg_unbeaten_sports",
        name="Unbeaten Sports Channel",
        name_en="Unbeaten Sports Channel",
        category="sport_global",
        url="https://d1t5afz6qed3xk.cloudfront.net/Unbeaten.m3u8",
        thumbnail="/israel_tv/logos/sg_unbeaten_sports.png",
    ),
    Channel(
        id="sg_usa_network_east",
        name="USA Network East",
        name_en="USA Network East",
        category="sport_global",
        url="https://tvpass.org/live/USANetworkEast/hd",
    ),
    Channel(
        id="sg_w14dk_all_sports",
        name="W14DK-D All Sports TV",
        name_en="W14DK-D All Sports Television Network",
        category="sport_global",
        url="https://2-fss-2.streamhoster.com/pl_118/204972-2205186-1/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_w14dk_all_sports.png",
    ),
    Channel(
        id="sg_willow_sports",
        name="Willow Sports",
        name_en="Willow Sports",
        category="sport_global",
        url="https://d36r8jifhgsk5j.cloudfront.net/Willow_TV.m3u8",
        thumbnail="/israel_tv/logos/sg_willow_sports.png",
    ),
    Channel(
        id="sg_world_of_freesports",
        name="World of Freesports",
        name_en="World of Freesports",
        category="sport_global",
        url="https://mainstreammedia-worldoffreesportsintl-rakuten.amagi.tv/hls/amagi_hls_data_rakutenAA-mainstreammediafreesportsintl-rakuten/CDN/master.m3u8",
        thumbnail="/israel_tv/logos/sg_world_of_freesports.png",
    ),
    Channel(
        id="sg_world_of_freesports_2",
        name="World of Freesports 2",
        name_en="World of Freesports 2",
        category="sport_global",
        url="https://mainstreammedia-worldoffreesportsintl-rakuten.amagi.tv/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_world_of_freesports_2.png",
    ),
    Channel(
        id="sg_world_poker_tour",
        name="World Poker Tour",
        name_en="World Poker Tour",
        category="sport_global",
        url="https://jmp2.uk/plu-5ad9b7aae738977e2c312132.m3u8",
        thumbnail="/israel_tv/logos/sg_world_poker_tour.png",
    ),
    Channel(
        id="sg_world_poker_tour_hd",
        name="World Poker Tour HD",
        name_en="World Poker Tour HD",
        category="sport_global",
        url="https://amg00477-samsungelectron-worldpokertour-samsunguk-81igb.amagi.tv/playlist/amg00477-samsungelectron-worldpokertour-samsunguk/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_world_poker_tour_hd.png",
    ),
    Channel(
        id="sg_astrakhan_sport",
        name="Астрахань Sport",
        name_en="Astrakhan Sport",
        category="sport_global",
        url="https://streaming.astrakhan.ru/astrakhanrusporthd/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_astrakhan_sport.png",
    ),
    Channel(
        id="sg_belarus_5",
        name="Беларусь 5",
        name_en="Belarus 5",
        category="sport_global",
        url="https://ngtrk.dc.beltelecom.by/ngtrk/smil:belarus5.smil/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_belarus_5.png",
    ),
    Channel(
        id="sg_belarus_5_int",
        name="Беларусь 5 Интернет",
        name_en="Belarus 5 International",
        category="sport_global",
        url="https://edge59.dc.beltelecom.by/ngtrk/smil:belarus5int.smil/playlist.m3u8",
        thumbnail="/israel_tv/logos/sg_belarus_5_int.png",
    ),
    Channel(
        id="sg_boks_tv",
        name="Бокс ТВ",
        name_en="Boks TV",
        category="sport_global",
        url="http://31.148.48.15/Boks_TV/index.m3u8",
        thumbnail="/israel_tv/logos/sg_boks_tv.png",
    ),
    Channel(
        id="sg_match_arena",
        name="МАТЧ! Арена",
        name_en="Match! Arena",
        category="sport_global",
        url="http://31.148.48.15/Match_Arena_HD/index.m3u8",
        thumbnail="/israel_tv/logos/sg_match_arena.png",
    ),
    Channel(
        id="sg_match_boets",
        name="МАТЧ! Боец",
        name_en="Match! Boets",
        category="sport_global",
        url="http://31.148.48.15/Match_Boec/index.m3u8",
        thumbnail="/israel_tv/logos/sg_match_boets.png",
    ),
    Channel(
        id="sg_match_igra",
        name="МАТЧ! Игра",
        name_en="Match! Igra",
        category="sport_global",
        url="http://31.148.48.15/Match_Igra_HD/index.m3u8",
        thumbnail="/israel_tv/logos/sg_match_igra.png",
    ),
    Channel(
        id="sg_match_planeta",
        name="Матч! Планета",
        name_en="Match! Planeta",
        category="sport_global",
        url="https://cdn4.skygo.mn/live/disk1/Match_Planeta/HLSv3-FTA/Match_Planeta.m3u8",
        thumbnail="/israel_tv/logos/sg_match_planeta.png",
    ),
    Channel(
        id="sg_russkiy_ekstrim",
        name="Русский Экстрим",
        name_en="Russkiy Ekstrim",
        category="sport_global",
        url="http://31.148.48.15/Russkiy_Ekstrim/index.m3u8",
        thumbnail="/israel_tv/logos/sg_russkiy_ekstrim.png",
    ),
    Channel(
        id="sg_futbol_hd",
        name="Футбол HD",
        name_en="Futbol HD",
        category="sport_global",
        url="http://31.148.48.15/Futbol_HD/index.m3u8",
        thumbnail="/israel_tv/logos/sg_futbol_hd.png",
    ),
]

CHANNELS_BY_ID: dict[str, Channel] = {ch.id: ch for ch in CHANNELS}


def get_channels_by_category(category: str) -> list[Channel]:
    """Return all channels belonging to the given category."""
    return [ch for ch in CHANNELS if ch.category == category]
